TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  NUM_CLASSES: 400
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_DIMENSIONS: [3, 3]
SLOWFAST:
  ALPHA: 8
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0001
SOLVER:
  BASE_LR: 0.16
  LR_POLICY: cosine
  MAX_EPOCH: 128
  WARMUP_EPOCHS: 25  # default: 25
  WARMUP_START_LR: 0.001
MODEL:
  NUM_CLASSES: 400
  ARCH: slowfast
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  SPLIT: val
  BATCH_SIZE: 64
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 8
OUTPUT_DIR: .
