TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  EVAL_FULL_VIDEO: True
  EVAL_NUM_FRAMES: 250
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 8
  TARGET_FPS: 25
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 13, 24]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 25
  MOMENTUM: 0.9
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: VIT
  MODEL_NAME: VTN
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
VTN:
  PRETRAINED: True
  MLP_DIM: 768
  DROP_PATH_RATE: 0.0
  DROP_RATE: 0.0
  HIDDEN_DIM: 768
  MAX_POSITION_EMBEDDINGS: 288
  NUM_ATTENTION_HEADS: 12
  NUM_HIDDEN_LAYERS: 3
  ATTENTION_MODE: 'sliding_chunks'
  PAD_TOKEN_ID: -1
  ATTENTION_WINDOW: [18, 18, 18]
  INTERMEDIATE_SIZE: 3072
  ATTENTION_PROBS_DROPOUT_PROB: 0.1
  HIDDEN_DROPOUT_PROB: 0.1
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: False