TRAIN:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 512
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True

DATA:
  # PATH_TO_DATA_DIR: path-to-imagenet-dir
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  NUM_FRAMES: 1
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
MVIT:
  PATCH_2D: True
  ZERO_DECAY_POS_CLS: False
  MODE: "conv"
  CLS_EMBED_ON: False
  PATCH_KERNEL: [16, 16]
  PATCH_STRIDE: [16, 16]
  PATCH_PADDING: [0, 0]
  EMBED_DIM: 384
  NUM_HEADS: 6
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.1
  DEPTH: 12
  NORM: "layernorm"
  POOL_KV_STRIDE: []
  SEPARATE_QKV : True
  REV:
    ENABLE: True
    RESPATH_FUSE: "concat"
    RES_PATH: "conv"
AUG:
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0005
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 70.0
  WARMUP_START_LR: 1e-8
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0 # this is commented now
MODEL:
  NUM_CLASSES: 1000
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: False
  DATASET: imagenet
  BATCH_SIZE: 256
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
