TASK: ssl_eval_ssv2
TRAIN:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 64
  EVAL_PERIOD: 4
  CHECKPOINT_PERIOD: 4
  AUTO_RESUME: True
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_CLEAR_NAME_PATTERN: ("backbone.",)
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  DECODING_BACKEND: torchvision
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  PATH_TO_DATA_DIR: # pls add
  PATH_PREFIX: # pls add
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.12
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 14, 18]
  MAX_EPOCH: 22
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 0.19
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 174
  ARCH: slow
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 8
RNG_SEED: 0
OUTPUT_DIR: .
