TASK: ssl
TRAIN:
  DATASET: kinetics
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
MODEL:
  NUM_CLASSES: 128
  MODEL_NAME: ContrastiveModel
  ARCH: slow
  LOSS_FUNC: contrastive_loss
  DROPOUT_RATE: 0.0
  HEAD_ACT: none
CONTRASTIVE:
  TYPE: simclr # default mem
  T: 0.1 # default 0.07
  DIM: 128 # 128 default, if changed, change nCls too
  NUM_CLASSES_DOWNSTREAM: 400
  NUM_MLP_LAYERS: 3 # default 1
  BN_SYNC_MLP: True
  SIMCLR_DIST_ON: True # default false
  SEQUENTIAL: True  # def fault
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_CROP_NUM_TEMPORAL: 4  # default 1
  TRAIN_CROP_NUM_SPATIAL: 1  # default 1
  SSL_MOCOV2_AUG: True
  SSL_COLOR_JITTER: True # default false
  TRAIN_JITTER_SCALES_RELATIVE: [0.2, 0.766]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_HUE: 0.15
  SSL_COLOR_BRI_CON_SAT: [0.6, 0.6, 0.6] # default [0.4, 0.4, 0.4]
  TRAIN_JITTER_SCALES: [224, 224]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_LABEL_SEPARATOR: " "
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
  NUM_SYNC_DEVICES: 8
  NORM_TYPE: "sync_batchnorm"
  # NORM_TYPE: "sync_batchnorm_apex"
SOLVER:
  BASE_LR: 0.6
  BASE_LR: 1.2

  LARS_ON: True
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 10
  PIN_MEMORY: True
NUM_GPUS: 8
RNG_SEED: 0
OUTPUT_DIR: .
