TASK: ssl
TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 100000
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  KILL_LOSS_EXPLOSION_FACTOR: 2.0 # default 0.0 (not enforced)
DATA:
  PATH_TO_DATA_DIR: /content/drive/MyDrive/Mae/data/
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: pyav
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  DECODING_SHORT_SIZE: 320
  TRAIN_JITTER_SCALES_RELATIVE: [0.5, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  TRAIN_CROP_NUM_TEMPORAL: 4  # default 1
MVIT:
  SEP_POS_EMBED: True
  PATCH_KERNEL: [2, 16, 16]
  PATCH_STRIDE: [2, 16, 16]
  PATCH_PADDING: [0, 0, 0]
  EMBED_DIM: 768
  NUM_HEADS: 12
  MLP_RATIO: 4.0
  QKV_BIAS: True
  NORM: "layernorm"
  DEPTH: 12
  DROPPATH_RATE: 0.0
  MODE: "conv"
  CLS_EMBED_ON: True
  # This must be TRUE to match the separate q, k, v keys in the checkpoint
  SEPARATE_QKV: True
MASK:
  ENABLE: True
  MAE_ON: True #  default False
  MAE_RND_MASK: True # default: false
  TIME_STRIDE_LOSS: True 
  PRETRAIN_DEPTH: [11]
  HEAD_TYPE: "separate_xformer"
  DECODER_DEPTH: 4
  DECODER_EMBED_DIM: 512
AUG:
  ENABLE: False
  COLOR_JITTER: None
  AA_TYPE: ""
  RE_PROB: 0.0
  MASK_RATIO: 0.9
MIXUP:
  ENABLE: False
SOLVER:
  CLIP_GRAD_L2NORM: 0.02
  BASE_LR: 1e-4
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  MAX_EPOCH: 200
  WARMUP_EPOCHS: 60.0
  BETAS: (0.9, 0.95) # default (0.9, 0.999)
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  ZERO_WD_1D_PARAM: True # default False
  WARMUP_START_LR: 1e-6
  OPTIMIZING_METHOD: adamw
MODEL:
  ARCH: maskmvit
  MODEL_NAME: MaskMViT
  LOSS_FUNC: multi_mse
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 3
  NUM_TEMPORAL_CLIPS: [7]
  CHECKPOINT_FILE_PATH: /content/drive/MyDrive/Mae/data/VIT_B_16x4_MAE_PT.pyth
  SAVE_RESULTS_CSV: preds_part_0_pt.csv

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /content/drive/MyDrive/Mae/output
LOG_MODEL_INFO: True
